# Generated by Django 2.0 on 2021-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('uploader', models.CharField(max_length=20)),
                ('vehicle', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('start', models.CharField(default='0', max_length=30)),
                ('end', models.CharField(default='0', max_length=30)),
                ('bagid', models.CharField(default='   ', max_length=100)),
            ],
        ),
    ]
