# Generated by Django 2.2.10 on 2020-08-11 19:47

from django.db import migrations


def create_data(apps, schema_editor):
    Bag = apps.get_model('app', 'Bag')
    Bag(country="China", city="Shenzhen", location="ces small", uploader="Yajun Wang",
        vehicle="MKZ001", description="bag 001 description", status="pending", start='0', end='10000').save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
