# Generated by Django 2.2.10 on 2020-08-11 19:47

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    ]
