# Generated by Django 2.2 on 2020-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='end',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='bag',
            name='start',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
