# Generated by Django 2.2 on 2020-08-12 17:02

from django.db import migrations, models


def create_data(apps, schema_editor):
    Bag = apps.get_model('app', 'Bag')
    Bag(country="China", city="Hangzhou", location="whart", uploader="Yajun Wang",
        vehicle="MKZ001", description="bag 002 description", status="pending", start='0', end='10000').save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200812_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='end',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='bag',
            name='start',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.RunPython(create_data),
    ]
