# Generated by Django 2.2 on 2020-08-13 03:26

from django.db import migrations, models


def create_data(apps, schema_editor):
    Bag = apps.get_model('app', 'Bag')
    Bag(bagid="highway_2", country="US", city="Fremont", location="highway", uploader="Yajun Wang",
        vehicle="MKZ001", description="bag highway_2 description", status="pending", start='0', end='1583635917767822810').save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200812_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bagid',
            field=models.CharField(default='   ', max_length=30),
        ),
        migrations.RunPython(create_data),
    ]
