# Generated by Django 2.2 on 2020-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200812_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bagid',
            field=models.CharField(default='   ', max_length=30, unique=True),
        ),
    ]
