# Generated by Django 2.2.10 on 2020-08-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200813_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bagid',
            field=models.CharField(default='   ', max_length=100, unique=True),
        ),
    ]
