apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: brucewong123/djangov2
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-ce", "cd data_hub && git pull && python3 manage.py runserver 0.0.0.0:8000" ]
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: django
  name: django-service
  namespace: planning-public-dev
spec:
  type: NodePort
  ports:
  - name: django
    port: 8000
    targetPort: 8000
    nodePort: 30004
  selector:
    app: django
