apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: django
  namespace: planning-public-dev
spec:
  rules:
  - host: "dataserver.planning.simulation.deeproute.ai"
    http:
      paths:
      - backend:
          serviceName: django-service
          servicePort: 8000