# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x63ommon.proto\"-\n\x06\x43\x61mera\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\x10\n\x08img_path\x18\x02 \x01(\t\"+\n\x08Vector3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"+\n\x08Vector3f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"+\n\x08Vector3i\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\" \n\x08Vector2d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\" \n\x08Vector2f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\" \n\x08Vector2i\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"&\n\tPolygon3d\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector3d\"&\n\tPolygon3f\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector3f\"&\n\tPolygon3i\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector3i\"\'\n\nPolyline3d\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector3d\"\'\n\nPolyline3f\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector3f\"\'\n\nPolyline3i\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector3i\"&\n\tPolygon2d\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector2d\"&\n\tPolygon2f\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector2f\"&\n\tPolygon2i\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector2i\"\'\n\nPolyline2d\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector2d\"\'\n\nPolyline2f\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector2f\"\'\n\nPolyline2i\x12\x19\n\x06points\x18\x01 \x03(\x0b\x32\t.Vector2i*5\n\x0bLabelStatus\x12\x0b\n\x07UNLABEL\x10\x00\x12\x0c\n\x08PRELABEL\x10\x01\x12\x0b\n\x07LABELED\x10\x02')
)

_LABELSTATUS = _descriptor.EnumDescriptor(
  name='LabelStatus',
  full_name='LabelStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNLABEL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRELABEL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LABELED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=786,
  serialized_end=839,
)
_sym_db.RegisterEnumDescriptor(_LABELSTATUS)

LabelStatus = enum_type_wrapper.EnumTypeWrapper(_LABELSTATUS)
UNLABEL = 0
PRELABEL = 1
LABELED = 2



_CAMERA = _descriptor.Descriptor(
  name='Camera',
  full_name='Camera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='Camera.camera_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_path', full_name='Camera.img_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=61,
)


_VECTOR3D = _descriptor.Descriptor(
  name='Vector3d',
  full_name='Vector3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector3d.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector3d.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vector3d.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=106,
)


_VECTOR3F = _descriptor.Descriptor(
  name='Vector3f',
  full_name='Vector3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector3f.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector3f.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vector3f.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=151,
)


_VECTOR3I = _descriptor.Descriptor(
  name='Vector3i',
  full_name='Vector3i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector3i.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector3i.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vector3i.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=196,
)


_VECTOR2D = _descriptor.Descriptor(
  name='Vector2d',
  full_name='Vector2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector2d.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector2d.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=230,
)


_VECTOR2F = _descriptor.Descriptor(
  name='Vector2f',
  full_name='Vector2f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector2f.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector2f.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=264,
)


_VECTOR2I = _descriptor.Descriptor(
  name='Vector2i',
  full_name='Vector2i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector2i.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector2i.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=298,
)


_POLYGON3D = _descriptor.Descriptor(
  name='Polygon3d',
  full_name='Polygon3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polygon3d.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=338,
)


_POLYGON3F = _descriptor.Descriptor(
  name='Polygon3f',
  full_name='Polygon3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polygon3f.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=378,
)


_POLYGON3I = _descriptor.Descriptor(
  name='Polygon3i',
  full_name='Polygon3i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polygon3i.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=418,
)


_POLYLINE3D = _descriptor.Descriptor(
  name='Polyline3d',
  full_name='Polyline3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polyline3d.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=459,
)


_POLYLINE3F = _descriptor.Descriptor(
  name='Polyline3f',
  full_name='Polyline3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polyline3f.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=500,
)


_POLYLINE3I = _descriptor.Descriptor(
  name='Polyline3i',
  full_name='Polyline3i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polyline3i.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=541,
)


_POLYGON2D = _descriptor.Descriptor(
  name='Polygon2d',
  full_name='Polygon2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polygon2d.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=581,
)


_POLYGON2F = _descriptor.Descriptor(
  name='Polygon2f',
  full_name='Polygon2f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polygon2f.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=621,
)


_POLYGON2I = _descriptor.Descriptor(
  name='Polygon2i',
  full_name='Polygon2i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polygon2i.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=661,
)


_POLYLINE2D = _descriptor.Descriptor(
  name='Polyline2d',
  full_name='Polyline2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polyline2d.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=702,
)


_POLYLINE2F = _descriptor.Descriptor(
  name='Polyline2f',
  full_name='Polyline2f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polyline2f.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=743,
)


_POLYLINE2I = _descriptor.Descriptor(
  name='Polyline2i',
  full_name='Polyline2i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polyline2i.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=784,
)

_POLYGON3D.fields_by_name['points'].message_type = _VECTOR3D
_POLYGON3F.fields_by_name['points'].message_type = _VECTOR3F
_POLYGON3I.fields_by_name['points'].message_type = _VECTOR3I
_POLYLINE3D.fields_by_name['points'].message_type = _VECTOR3D
_POLYLINE3F.fields_by_name['points'].message_type = _VECTOR3F
_POLYLINE3I.fields_by_name['points'].message_type = _VECTOR3I
_POLYGON2D.fields_by_name['points'].message_type = _VECTOR2D
_POLYGON2F.fields_by_name['points'].message_type = _VECTOR2F
_POLYGON2I.fields_by_name['points'].message_type = _VECTOR2I
_POLYLINE2D.fields_by_name['points'].message_type = _VECTOR2D
_POLYLINE2F.fields_by_name['points'].message_type = _VECTOR2F
_POLYLINE2I.fields_by_name['points'].message_type = _VECTOR2I
DESCRIPTOR.message_types_by_name['Camera'] = _CAMERA
DESCRIPTOR.message_types_by_name['Vector3d'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Vector3f'] = _VECTOR3F
DESCRIPTOR.message_types_by_name['Vector3i'] = _VECTOR3I
DESCRIPTOR.message_types_by_name['Vector2d'] = _VECTOR2D
DESCRIPTOR.message_types_by_name['Vector2f'] = _VECTOR2F
DESCRIPTOR.message_types_by_name['Vector2i'] = _VECTOR2I
DESCRIPTOR.message_types_by_name['Polygon3d'] = _POLYGON3D
DESCRIPTOR.message_types_by_name['Polygon3f'] = _POLYGON3F
DESCRIPTOR.message_types_by_name['Polygon3i'] = _POLYGON3I
DESCRIPTOR.message_types_by_name['Polyline3d'] = _POLYLINE3D
DESCRIPTOR.message_types_by_name['Polyline3f'] = _POLYLINE3F
DESCRIPTOR.message_types_by_name['Polyline3i'] = _POLYLINE3I
DESCRIPTOR.message_types_by_name['Polygon2d'] = _POLYGON2D
DESCRIPTOR.message_types_by_name['Polygon2f'] = _POLYGON2F
DESCRIPTOR.message_types_by_name['Polygon2i'] = _POLYGON2I
DESCRIPTOR.message_types_by_name['Polyline2d'] = _POLYLINE2D
DESCRIPTOR.message_types_by_name['Polyline2f'] = _POLYLINE2F
DESCRIPTOR.message_types_by_name['Polyline2i'] = _POLYLINE2I
DESCRIPTOR.enum_types_by_name['LabelStatus'] = _LABELSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Camera = _reflection.GeneratedProtocolMessageType('Camera', (_message.Message,), dict(
  DESCRIPTOR = _CAMERA,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Camera)
  ))
_sym_db.RegisterMessage(Camera)

Vector3d = _reflection.GeneratedProtocolMessageType('Vector3d', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3D,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Vector3d)
  ))
_sym_db.RegisterMessage(Vector3d)

Vector3f = _reflection.GeneratedProtocolMessageType('Vector3f', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3F,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Vector3f)
  ))
_sym_db.RegisterMessage(Vector3f)

Vector3i = _reflection.GeneratedProtocolMessageType('Vector3i', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3I,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Vector3i)
  ))
_sym_db.RegisterMessage(Vector3i)

Vector2d = _reflection.GeneratedProtocolMessageType('Vector2d', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR2D,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Vector2d)
  ))
_sym_db.RegisterMessage(Vector2d)

Vector2f = _reflection.GeneratedProtocolMessageType('Vector2f', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR2F,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Vector2f)
  ))
_sym_db.RegisterMessage(Vector2f)

Vector2i = _reflection.GeneratedProtocolMessageType('Vector2i', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR2I,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Vector2i)
  ))
_sym_db.RegisterMessage(Vector2i)

Polygon3d = _reflection.GeneratedProtocolMessageType('Polygon3d', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON3D,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polygon3d)
  ))
_sym_db.RegisterMessage(Polygon3d)

Polygon3f = _reflection.GeneratedProtocolMessageType('Polygon3f', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON3F,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polygon3f)
  ))
_sym_db.RegisterMessage(Polygon3f)

Polygon3i = _reflection.GeneratedProtocolMessageType('Polygon3i', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON3I,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polygon3i)
  ))
_sym_db.RegisterMessage(Polygon3i)

Polyline3d = _reflection.GeneratedProtocolMessageType('Polyline3d', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE3D,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polyline3d)
  ))
_sym_db.RegisterMessage(Polyline3d)

Polyline3f = _reflection.GeneratedProtocolMessageType('Polyline3f', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE3F,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polyline3f)
  ))
_sym_db.RegisterMessage(Polyline3f)

Polyline3i = _reflection.GeneratedProtocolMessageType('Polyline3i', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE3I,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polyline3i)
  ))
_sym_db.RegisterMessage(Polyline3i)

Polygon2d = _reflection.GeneratedProtocolMessageType('Polygon2d', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON2D,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polygon2d)
  ))
_sym_db.RegisterMessage(Polygon2d)

Polygon2f = _reflection.GeneratedProtocolMessageType('Polygon2f', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON2F,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polygon2f)
  ))
_sym_db.RegisterMessage(Polygon2f)

Polygon2i = _reflection.GeneratedProtocolMessageType('Polygon2i', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON2I,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polygon2i)
  ))
_sym_db.RegisterMessage(Polygon2i)

Polyline2d = _reflection.GeneratedProtocolMessageType('Polyline2d', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE2D,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polyline2d)
  ))
_sym_db.RegisterMessage(Polyline2d)

Polyline2f = _reflection.GeneratedProtocolMessageType('Polyline2f', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE2F,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polyline2f)
  ))
_sym_db.RegisterMessage(Polyline2f)

Polyline2i = _reflection.GeneratedProtocolMessageType('Polyline2i', (_message.Message,), dict(
  DESCRIPTOR = _POLYLINE2I,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:Polyline2i)
  ))
_sym_db.RegisterMessage(Polyline2i)


# @@protoc_insertion_point(module_scope)
