# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto


from google.protobuf import descriptor_pb2
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import labeling.semantic_3d_pb2 as semantic__3d__pb2  # NOQA: E402
import labeling.semantic_2d_pb2 as semantic__2d__pb2  # NOQA: E402
import labeling.object_3d_pb2 as object__3d__pb2  # NOQA: E402
import labeling.object_2d_pb2 as object__2d__pb2  # NOQA: E402
import labeling.common_pb2 as common__pb2  # NOQA: E402
DESCRIPTOR = _descriptor.FileDescriptor(
    name='frame.proto',
    package='',
    syntax='proto2',
    serialized_pb=_b('\n\x0b\x66rame.proto\x1a\x0c\x63ommon.proto\x1a\x0fobject_2d.proto\x1a\x0fobject_3d.proto\x1a\x11semantic_2d.proto\x1a\x11semantic_3d.proto\"\xbe\x03\n\x0f\x41nnotationFrame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x03\x12\x12\n\ntime_stamp\x18\x02 \x01(\t\x12\x1b\n\x08position\x18\x03 \x01(\x0b\x32\t.Vector3d\x12\x1b\n\x08rotation\x18\x04 \x01(\x0b\x32\t.Vector3d\x12\x30\n\x11objects_3d_status\x18\x05 \x01(\x0e\x32\x0c.LabelStatus:\x07UNLABEL\x12\x1e\n\nobjects_3d\x18\x06 \x01(\x0b\x32\n.Objects3D\x12\x30\n\x11objects_2d_status\x18\x07 \x01(\x0e\x32\x0c.LabelStatus:\x07UNLABEL\x12\x1d\n\nobjects_2d\x18\x08 \x03(\x0b\x32\t.Object2D\x12\x31\n\x12semantic_3d_status\x18\t \x01(\x0e\x32\x0c.LabelStatus:\x07UNLABEL\x12 \n\x0bsemantic_3d\x18\n \x01(\x0b\x32\x0b.Semantic3D\x12\x31\n\x12semantic_2d_status\x18\x0b \x01(\x0e\x32\x0c.LabelStatus:\x07UNLABEL\x12 \n\x0bsemantic_2d\x18\x0c \x03(\x0b\x32\x0b.Semantic2D'),
    dependencies=[common__pb2.DESCRIPTOR, object__2d__pb2.DESCRIPTOR, object__3d__pb2.DESCRIPTOR, semantic__2d__pb2.DESCRIPTOR, semantic__3d__pb2.DESCRIPTOR, ])


_ANNOTATIONFRAME = _descriptor.Descriptor(
    name='AnnotationFrame',
    full_name='AnnotationFrame',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='frame_id', full_name='AnnotationFrame.frame_id', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='time_stamp', full_name='AnnotationFrame.time_stamp', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='position', full_name='AnnotationFrame.position', index=2,
            number=3, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='rotation', full_name='AnnotationFrame.rotation', index=3,
            number=4, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='objects_3d_status', full_name='AnnotationFrame.objects_3d_status', index=4,
            number=5, type=14, cpp_type=8, label=1,
            has_default_value=True, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='objects_3d', full_name='AnnotationFrame.objects_3d', index=5,
            number=6, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='objects_2d_status', full_name='AnnotationFrame.objects_2d_status', index=6,
            number=7, type=14, cpp_type=8, label=1,
            has_default_value=True, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='objects_2d', full_name='AnnotationFrame.objects_2d', index=7,
            number=8, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='semantic_3d_status', full_name='AnnotationFrame.semantic_3d_status', index=8,
            number=9, type=14, cpp_type=8, label=1,
            has_default_value=True, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='semantic_3d', full_name='AnnotationFrame.semantic_3d', index=9,
            number=10, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='semantic_2d_status', full_name='AnnotationFrame.semantic_2d_status', index=10,
            number=11, type=14, cpp_type=8, label=1,
            has_default_value=True, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='semantic_2d', full_name='AnnotationFrame.semantic_2d', index=11,
            number=12, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=102,
    serialized_end=548,
)

_ANNOTATIONFRAME.fields_by_name['position'].message_type = common__pb2._VECTOR3D
_ANNOTATIONFRAME.fields_by_name['rotation'].message_type = common__pb2._VECTOR3D
_ANNOTATIONFRAME.fields_by_name['objects_3d_status'].enum_type = common__pb2._LABELSTATUS
_ANNOTATIONFRAME.fields_by_name['objects_3d'].message_type = object__3d__pb2._OBJECTS3D
_ANNOTATIONFRAME.fields_by_name['objects_2d_status'].enum_type = common__pb2._LABELSTATUS
_ANNOTATIONFRAME.fields_by_name['objects_2d'].message_type = object__2d__pb2._OBJECT2D
_ANNOTATIONFRAME.fields_by_name['semantic_3d_status'].enum_type = common__pb2._LABELSTATUS
_ANNOTATIONFRAME.fields_by_name['semantic_3d'].message_type = semantic__3d__pb2._SEMANTIC3D
_ANNOTATIONFRAME.fields_by_name['semantic_2d_status'].enum_type = common__pb2._LABELSTATUS
_ANNOTATIONFRAME.fields_by_name['semantic_2d'].message_type = semantic__2d__pb2._SEMANTIC2D
DESCRIPTOR.message_types_by_name['AnnotationFrame'] = _ANNOTATIONFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnnotationFrame = _reflection.GeneratedProtocolMessageType('AnnotationFrame', (_message.Message,), dict(
    DESCRIPTOR=_ANNOTATIONFRAME,
    __module__='frame_pb2'
    # @@protoc_insertion_point(class_scope:AnnotationFrame)
))
_sym_db.RegisterMessage(AnnotationFrame)


# @@protoc_insertion_point(module_scope)
