# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_3d.proto


from google.protobuf import descriptor_pb2
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
import labeling.common_pb2 as common__pb2  # NOQA: E402

DESCRIPTOR = _descriptor.FileDescriptor(
    name='object_3d.proto',
    package='',
    syntax='proto2',
    serialized_pb=_b('\n\x0fobject_3d.proto\x1a\x0c\x63ommon.proto\"\xec\x04\n\tObjects3D\x12&\n\tobject_3d\x18\x01 \x03(\x0b\x32\x13.Objects3D.Object3D\x1a\xb6\x04\n\x08Object3D\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x0e\n\x06length\x18\x05 \x01(\x01\x12\r\n\x05width\x18\x06 \x01(\x01\x12\x0e\n\x06height\x18\x07 \x01(\x01\x12\x0f\n\x07heading\x18\x08 \x01(\x01\x12\x31\n\nbasic_type\x18\t \x01(\x0e\x32\x1d.Objects3D.Object3D.BasicType\x12\x1b\n\x08velocity\x18\n \x01(\x0b\x32\t.Vector3d\x12\x18\n\x10points_in_object\x18\x0b \x01(\x05\"\xd2\x02\n\tBasicType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03\x43\x41R\x10\x01\x12\x0e\n\nPEDESTRIAN\x10\x02\x12\x0b\n\x07\x43YCLIST\x10\x03\x12\x08\n\x04\x43ONE\x10\x04\x12\x07\n\x03VAN\x10\x05\x12\x07\n\x03\x42US\x10\x06\x12\t\n\x05TRUCK\x10\x07\x12\r\n\tBIG_TRUCK\x10\x08\x12\x0c\n\x08TRICYCLE\x10\t\x12\x0e\n\nBACKGROUND\x10\n\x12\x11\n\rSTATIC_OBJECT\x10\x0b\x12\x0f\n\x0bSTATIC_BIKE\x10\x0c\x12\n\n\x06\x41NIMAL\x10\r\x12\x0b\n\x07RAILING\x10\x0e\x12\r\n\tDONT_CARE\x10\x0f\x12\x0c\n\x08\x43\x41R_HARD\x10\x10\x12\x13\n\x0fPEDESTRIAN_HARD\x10\x11\x12\x10\n\x0c\x43YCLIST_HARD\x10\x12\x12\x11\n\rTRICYCLE_HARD\x10\x13\x12\x0c\n\x08VAN_HARD\x10\x14\x12\x0c\n\x08\x42US_HARD\x10\x15\x12\x0e\n\nTRUCK_HARD\x10\x16'),
    dependencies=[common__pb2.DESCRIPTOR, ])


_OBJECTS3D_OBJECT3D_BASICTYPE = _descriptor.EnumDescriptor(
    name='BasicType',
    full_name='Objects3D.Object3D.BasicType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='UNKNOWN', index=0, number=0,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CAR', index=1, number=1,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='PEDESTRIAN', index=2, number=2,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CYCLIST', index=3, number=3,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CONE', index=4, number=4,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='VAN', index=5, number=5,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='BUS', index=6, number=6,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TRUCK', index=7, number=7,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='BIG_TRUCK', index=8, number=8,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TRICYCLE', index=9, number=9,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='BACKGROUND', index=10, number=10,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='STATIC_OBJECT', index=11, number=11,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='STATIC_BIKE', index=12, number=12,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='ANIMAL', index=13, number=13,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='RAILING', index=14, number=14,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='DONT_CARE', index=15, number=15,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CAR_HARD', index=16, number=16,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='PEDESTRIAN_HARD', index=17, number=17,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CYCLIST_HARD', index=18, number=18,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TRICYCLE_HARD', index=19, number=19,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='VAN_HARD', index=20, number=20,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='BUS_HARD', index=21, number=21,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TRUCK_HARD', index=22, number=22,
            options=None,
            type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=316,
    serialized_end=654,
)
_sym_db.RegisterEnumDescriptor(_OBJECTS3D_OBJECT3D_BASICTYPE)


_OBJECTS3D_OBJECT3D = _descriptor.Descriptor(
    name='Object3D',
    full_name='Objects3D.Object3D',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='Objects3D.Object3D.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='x', full_name='Objects3D.Object3D.x', index=1,
            number=2, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='y', full_name='Objects3D.Object3D.y', index=2,
            number=3, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='z', full_name='Objects3D.Object3D.z', index=3,
            number=4, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='length', full_name='Objects3D.Object3D.length', index=4,
            number=5, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='width', full_name='Objects3D.Object3D.width', index=5,
            number=6, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='height', full_name='Objects3D.Object3D.height', index=6,
            number=7, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='heading', full_name='Objects3D.Object3D.heading', index=7,
            number=8, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='basic_type', full_name='Objects3D.Object3D.basic_type', index=8,
            number=9, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='velocity', full_name='Objects3D.Object3D.velocity', index=9,
            number=10, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='points_in_object', full_name='Objects3D.Object3D.points_in_object', index=10,
            number=11, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _OBJECTS3D_OBJECT3D_BASICTYPE,
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=88,
    serialized_end=654,
)

_OBJECTS3D = _descriptor.Descriptor(
    name='Objects3D',
    full_name='Objects3D',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='object_3d', full_name='Objects3D.object_3d', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_OBJECTS3D_OBJECT3D, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=34,
    serialized_end=654,
)

_OBJECTS3D_OBJECT3D.fields_by_name['basic_type'].enum_type = _OBJECTS3D_OBJECT3D_BASICTYPE
_OBJECTS3D_OBJECT3D.fields_by_name['velocity'].message_type = common__pb2._VECTOR3D
_OBJECTS3D_OBJECT3D.containing_type = _OBJECTS3D
_OBJECTS3D_OBJECT3D_BASICTYPE.containing_type = _OBJECTS3D_OBJECT3D
_OBJECTS3D.fields_by_name['object_3d'].message_type = _OBJECTS3D_OBJECT3D
DESCRIPTOR.message_types_by_name['Objects3D'] = _OBJECTS3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Objects3D = _reflection.GeneratedProtocolMessageType('Objects3D', (_message.Message,), dict(

    Object3D=_reflection.GeneratedProtocolMessageType('Object3D', (_message.Message,), dict(
        DESCRIPTOR=_OBJECTS3D_OBJECT3D,
        __module__='object_3d_pb2'
        # @@protoc_insertion_point(class_scope:Objects3D.Object3D)
    )),
    DESCRIPTOR=_OBJECTS3D,
    __module__='object_3d_pb2'
    # @@protoc_insertion_point(class_scope:Objects3D)
))
_sym_db.RegisterMessage(Objects3D)
_sym_db.RegisterMessage(Objects3D.Object3D)


# @@protoc_insertion_point(module_scope)
