# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perception_labeling_dataserver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='perception_labeling_dataserver.proto',
  package='perception.labeling',
  syntax='proto2',
  serialized_pb=_b('\n$perception_labeling_dataserver.proto\x12\x13perception.labeling\"E\n\nTimeStruct\x12\x13\n\x0b\x66rame_index\x18\x01 \x02(\x05\x12\x11\n\ttimestamp\x18\x02 \x02(\t\x12\x0f\n\x07rostime\x18\x03 \x02(\t\"5\n\x08IndexMap\x12\x15\n\rvirtual_index\x18\x01 \x02(\x05\x12\x12\n\nreal_index\x18\x02 \x02(\x05\"\x8d\x02\n\x0bPlDsRequest\x12\x0f\n\x07\x62\x61gName\x18\x01 \x02(\t\x12G\n\x0e\x64\x61taServerType\x18\x02 \x02(\x0e\x32/.perception.labeling.PlDsRequest.DataServerType\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x33\n\ntimeStruct\x18\x04 \x03(\x0b\x32\x1f.perception.labeling.TimeStruct\x12/\n\x08indexMap\x18\x05 \x03(\x0b\x32\x1d.perception.labeling.IndexMap\"/\n\x0e\x44\x61taServerType\x12\t\n\x05INDEX\x10\x01\x12\x08\n\x04TIME\x10\x02\x12\x08\n\x04\x44\x41TA\x10\x03\"\xfb\x02\n\x0cPlDsResponse\x12\x36\n\x03\x65rr\x18\x01 \x02(\x0e\x32).perception.labeling.PlDsResponse.ErrCode\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61gName\x18\x03 \x02(\t\x12\r\n\x05topic\x18\x04 \x01(\t\x12H\n\x0e\x64\x61taServerType\x18\x05 \x01(\x0e\x32\x30.perception.labeling.PlDsResponse.DataServerType\x12\x33\n\ntimeStruct\x18\x06 \x03(\x0b\x32\x1f.perception.labeling.TimeStruct\x12/\n\x08indexMap\x18\x07 \x03(\x0b\x32\x1d.perception.labeling.IndexMap\"\"\n\x07\x45rrCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"/\n\x0e\x44\x61taServerType\x12\t\n\x05INDEX\x10\x01\x12\x08\n\x04TIME\x10\x02\x12\x08\n\x04\x44\x41TA\x10\x03')
)



_PLDSREQUEST_DATASERVERTYPE = _descriptor.EnumDescriptor(
  name='DataServerType',
  full_name='perception.labeling.PlDsRequest.DataServerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDEX', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIME', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=410,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_PLDSREQUEST_DATASERVERTYPE)

_PLDSRESPONSE_ERRCODE = _descriptor.EnumDescriptor(
  name='ErrCode',
  full_name='perception.labeling.PlDsResponse.ErrCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=756,
  serialized_end=790,
)
_sym_db.RegisterEnumDescriptor(_PLDSRESPONSE_ERRCODE)

_PLDSRESPONSE_DATASERVERTYPE = _descriptor.EnumDescriptor(
  name='DataServerType',
  full_name='perception.labeling.PlDsResponse.DataServerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDEX', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIME', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=410,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_PLDSRESPONSE_DATASERVERTYPE)


_TIMESTRUCT = _descriptor.Descriptor(
  name='TimeStruct',
  full_name='perception.labeling.TimeStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_index', full_name='perception.labeling.TimeStruct.frame_index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='perception.labeling.TimeStruct.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rostime', full_name='perception.labeling.TimeStruct.rostime', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=130,
)


_INDEXMAP = _descriptor.Descriptor(
  name='IndexMap',
  full_name='perception.labeling.IndexMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='virtual_index', full_name='perception.labeling.IndexMap.virtual_index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real_index', full_name='perception.labeling.IndexMap.real_index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=185,
)


_PLDSREQUEST = _descriptor.Descriptor(
  name='PlDsRequest',
  full_name='perception.labeling.PlDsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bagName', full_name='perception.labeling.PlDsRequest.bagName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataServerType', full_name='perception.labeling.PlDsRequest.dataServerType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='perception.labeling.PlDsRequest.topic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStruct', full_name='perception.labeling.PlDsRequest.timeStruct', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indexMap', full_name='perception.labeling.PlDsRequest.indexMap', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLDSREQUEST_DATASERVERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=457,
)


_PLDSRESPONSE = _descriptor.Descriptor(
  name='PlDsResponse',
  full_name='perception.labeling.PlDsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='perception.labeling.PlDsResponse.err', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='perception.labeling.PlDsResponse.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bagName', full_name='perception.labeling.PlDsResponse.bagName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='perception.labeling.PlDsResponse.topic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataServerType', full_name='perception.labeling.PlDsResponse.dataServerType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStruct', full_name='perception.labeling.PlDsResponse.timeStruct', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indexMap', full_name='perception.labeling.PlDsResponse.indexMap', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLDSRESPONSE_ERRCODE,
    _PLDSRESPONSE_DATASERVERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=839,
)

_PLDSREQUEST.fields_by_name['dataServerType'].enum_type = _PLDSREQUEST_DATASERVERTYPE
_PLDSREQUEST.fields_by_name['timeStruct'].message_type = _TIMESTRUCT
_PLDSREQUEST.fields_by_name['indexMap'].message_type = _INDEXMAP
_PLDSREQUEST_DATASERVERTYPE.containing_type = _PLDSREQUEST
_PLDSRESPONSE.fields_by_name['err'].enum_type = _PLDSRESPONSE_ERRCODE
_PLDSRESPONSE.fields_by_name['dataServerType'].enum_type = _PLDSRESPONSE_DATASERVERTYPE
_PLDSRESPONSE.fields_by_name['timeStruct'].message_type = _TIMESTRUCT
_PLDSRESPONSE.fields_by_name['indexMap'].message_type = _INDEXMAP
_PLDSRESPONSE_ERRCODE.containing_type = _PLDSRESPONSE
_PLDSRESPONSE_DATASERVERTYPE.containing_type = _PLDSRESPONSE
DESCRIPTOR.message_types_by_name['TimeStruct'] = _TIMESTRUCT
DESCRIPTOR.message_types_by_name['IndexMap'] = _INDEXMAP
DESCRIPTOR.message_types_by_name['PlDsRequest'] = _PLDSREQUEST
DESCRIPTOR.message_types_by_name['PlDsResponse'] = _PLDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeStruct = _reflection.GeneratedProtocolMessageType('TimeStruct', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTRUCT,
  __module__ = 'perception_labeling_dataserver_pb2'
  # @@protoc_insertion_point(class_scope:perception.labeling.TimeStruct)
  ))
_sym_db.RegisterMessage(TimeStruct)

IndexMap = _reflection.GeneratedProtocolMessageType('IndexMap', (_message.Message,), dict(
  DESCRIPTOR = _INDEXMAP,
  __module__ = 'perception_labeling_dataserver_pb2'
  # @@protoc_insertion_point(class_scope:perception.labeling.IndexMap)
  ))
_sym_db.RegisterMessage(IndexMap)

PlDsRequest = _reflection.GeneratedProtocolMessageType('PlDsRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLDSREQUEST,
  __module__ = 'perception_labeling_dataserver_pb2'
  # @@protoc_insertion_point(class_scope:perception.labeling.PlDsRequest)
  ))
_sym_db.RegisterMessage(PlDsRequest)

PlDsResponse = _reflection.GeneratedProtocolMessageType('PlDsResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLDSRESPONSE,
  __module__ = 'perception_labeling_dataserver_pb2'
  # @@protoc_insertion_point(class_scope:perception.labeling.PlDsResponse)
  ))
_sym_db.RegisterMessage(PlDsResponse)


# @@protoc_insertion_point(module_scope)
