# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_speed_bump.proto

from google.protobuf import descriptor_pb2
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import map_geometry_pb2 as map__geometry__pb2  # NOQA: E402


DESCRIPTOR = _descriptor.FileDescriptor(
    name='map_speed_bump.proto',
    package='deeproute.hdmap',
    syntax='proto2',
    serialized_pb=_b('\n\x14map_speed_bump.proto\x12\x0f\x64\x65\x65proute.hdmap\x1a\x12map_geometry.proto\"U\n\tSpeedBump\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\noverlap_id\x18\x02 \x03(\x05\x12(\n\x08position\x18\x03 \x03(\x0b\x32\x16.deeproute.hdmap.Curve'),
    dependencies=[map__geometry__pb2.DESCRIPTOR, ])


_SPEEDBUMP = _descriptor.Descriptor(
    name='SpeedBump',
    full_name='deeproute.hdmap.SpeedBump',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='deeproute.hdmap.SpeedBump.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='overlap_id', full_name='deeproute.hdmap.SpeedBump.overlap_id', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='position', full_name='deeproute.hdmap.SpeedBump.position', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=61,
    serialized_end=146,
)

_SPEEDBUMP.fields_by_name['position'].message_type = map__geometry__pb2._CURVE
DESCRIPTOR.message_types_by_name['SpeedBump'] = _SPEEDBUMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeedBump = _reflection.GeneratedProtocolMessageType('SpeedBump', (_message.Message,), dict(
    DESCRIPTOR=_SPEEDBUMP,
    __module__='map_speed_bump_pb2'
    # @@protoc_insertion_point(class_scope:deeproute.hdmap.SpeedBump)
))
_sym_db.RegisterMessage(SpeedBump)


# @@protoc_insertion_point(module_scope)
