# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_junction.proto

from google.protobuf import descriptor_pb2
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2  # NOQA: E402


DESCRIPTOR = _descriptor.FileDescriptor(
    name='map_junction.proto',
    package='deeproute.hdmap',
    syntax='proto2',
    serialized_pb=_b('\n\x12map_junction.proto\x12\x0f\x64\x65\x65proute.hdmap\x1a\x0egeometry.proto\"\xae\x01\n\x08Junction\x12\n\n\x02id\x18\x01 \x01(\x05\x12,\n\x07polygon\x18\x02 \x01(\x0b\x32\x1b.deeproute.geometry.Polygon\x12\x12\n\noverlap_id\x18\x03 \x03(\x05\x12\x13\n\x07lane_id\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x18\n\x0c\x63rosswalk_id\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x17\n\x0bstopline_id\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x0c\n\x04\x63ost\x18\x07 \x01(\x01'),
    dependencies=[geometry__pb2.DESCRIPTOR, ])


_JUNCTION = _descriptor.Descriptor(
    name='Junction',
    full_name='deeproute.hdmap.Junction',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='deeproute.hdmap.Junction.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='polygon', full_name='deeproute.hdmap.Junction.polygon', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='overlap_id', full_name='deeproute.hdmap.Junction.overlap_id', index=2,
            number=3, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lane_id', full_name='deeproute.hdmap.Junction.lane_id', index=3,
            number=4, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='crosswalk_id', full_name='deeproute.hdmap.Junction.crosswalk_id', index=4,
            number=5, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='stopline_id', full_name='deeproute.hdmap.Junction.stopline_id', index=5,
            number=6, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cost', full_name='deeproute.hdmap.Junction.cost', index=6,
            number=7, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=56,
    serialized_end=230,
)

_JUNCTION.fields_by_name['polygon'].message_type = geometry__pb2._POLYGON
DESCRIPTOR.message_types_by_name['Junction'] = _JUNCTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Junction = _reflection.GeneratedProtocolMessageType('Junction', (_message.Message,), dict(
    DESCRIPTOR=_JUNCTION,
    __module__='map_junction_pb2'
    # @@protoc_insertion_point(class_scope:deeproute.hdmap.Junction)
))
_sym_db.RegisterMessage(Junction)


_JUNCTION.fields_by_name['lane_id'].has_options = True
_JUNCTION.fields_by_name['lane_id']._options = _descriptor._ParseOptions(
    descriptor_pb2.FieldOptions(), _b('\020\001'))
_JUNCTION.fields_by_name['crosswalk_id'].has_options = True
_JUNCTION.fields_by_name['crosswalk_id']._options = _descriptor._ParseOptions(
    descriptor_pb2.FieldOptions(), _b('\020\001'))
_JUNCTION.fields_by_name['stopline_id'].has_options = True
_JUNCTION.fields_by_name['stopline_id']._options = _descriptor._ParseOptions(
    descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
