# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_stop_sign.proto

from google.protobuf import descriptor_pb2
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import map_geometry_pb2 as map__geometry__pb2  # NOQA: E402
import geometry_pb2 as geometry__pb2  # NOQA: E402


DESCRIPTOR = _descriptor.FileDescriptor(
    name='map_stop_sign.proto',
    package='deeproute.hdmap',
    syntax='proto2',
    serialized_pb=_b(
        '\n\x13map_stop_sign.proto\x12\x0f\x64\x65\x65proute.hdmap\x1a\x12map_geometry.proto\x1a\x0egeometry.proto\"\xa1\x02\n\x08StopSign\x12\n\n\x02id\x18\x01 \x01(\x05\x12)\n\tstop_line\x18\x02 \x03(\x0b\x32\x16.deeproute.hdmap.Curve\x12\x12\n\noverlap_id\x18\x03 \x03(\x05\x12\x30\n\x04type\x18\x04 \x01(\x0e\x32\".deeproute.hdmap.StopSign.StopType\x12-\n\x08location\x18\x05 \x01(\x0b\x32\x1b.deeproute.geometry.Point3D\x12\x0c\n\x04\x63ost\x18\x06 \x01(\x01\"[\n\x08StopType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07ONE_WAY\x10\x01\x12\x0b\n\x07TWO_WAY\x10\x02\x12\r\n\tTHREE_WAY\x10\x03\x12\x0c\n\x08\x46OUR_WAY\x10\x04\x12\x0b\n\x07\x41LL_WAY\x10\x05\"\xd6\x01\n\x08StopLine\x12\n\n\x02id\x18\x01 \x01(\x05\x12/\n\tstop_line\x18\x02 \x01(\x0b\x32\x1c.deeproute.geometry.Polyline\x12\x14\n\x0cstop_sign_id\x18\x03 \x01(\x05\x12\x15\n\ryield_sign_id\x18\x04 \x01(\x05\x12\x1c\n\x10traffic_light_id\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x0c\n\x04\x63ost\x18\x06 \x01(\x01\x12\x1a\n\x12yield_stop_line_id\x18\x07 \x01(\x05\x12\x18\n\x10yield_to_lane_id\x18\x08 \x03(\x05'),
    dependencies=[map__geometry__pb2.DESCRIPTOR, geometry__pb2.DESCRIPTOR, ])


_STOPSIGN_STOPTYPE = _descriptor.EnumDescriptor(
    name='StopType',
    full_name='deeproute.hdmap.StopSign.StopType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='UNKNOWN', index=0, number=0,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='ONE_WAY', index=1, number=1,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='TWO_WAY', index=2, number=2,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='THREE_WAY', index=3, number=3,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='FOUR_WAY', index=4, number=4,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='ALL_WAY', index=5, number=5,
            options=None,
            type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=275,
    serialized_end=366,
)
_sym_db.RegisterEnumDescriptor(_STOPSIGN_STOPTYPE)


_STOPSIGN = _descriptor.Descriptor(
    name='StopSign',
    full_name='deeproute.hdmap.StopSign',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='deeproute.hdmap.StopSign.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='stop_line', full_name='deeproute.hdmap.StopSign.stop_line', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='overlap_id', full_name='deeproute.hdmap.StopSign.overlap_id', index=2,
            number=3, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='type', full_name='deeproute.hdmap.StopSign.type', index=3,
            number=4, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='location', full_name='deeproute.hdmap.StopSign.location', index=4,
            number=5, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cost', full_name='deeproute.hdmap.StopSign.cost', index=5,
            number=6, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _STOPSIGN_STOPTYPE,
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=77,
    serialized_end=366,
)


_STOPLINE = _descriptor.Descriptor(
    name='StopLine',
    full_name='deeproute.hdmap.StopLine',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='id', full_name='deeproute.hdmap.StopLine.id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='stop_line', full_name='deeproute.hdmap.StopLine.stop_line', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='stop_sign_id', full_name='deeproute.hdmap.StopLine.stop_sign_id', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='yield_sign_id', full_name='deeproute.hdmap.StopLine.yield_sign_id', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='traffic_light_id', full_name='deeproute.hdmap.StopLine.traffic_light_id', index=4,
            number=5, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cost', full_name='deeproute.hdmap.StopLine.cost', index=5,
            number=6, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='yield_stop_line_id', full_name='deeproute.hdmap.StopLine.yield_stop_line_id', index=6,
            number=7, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='yield_to_lane_id', full_name='deeproute.hdmap.StopLine.yield_to_lane_id', index=7,
            number=8, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=369,
    serialized_end=583,
)

_STOPSIGN.fields_by_name['stop_line'].message_type = map__geometry__pb2._CURVE
_STOPSIGN.fields_by_name['type'].enum_type = _STOPSIGN_STOPTYPE
_STOPSIGN.fields_by_name['location'].message_type = geometry__pb2._POINT3D
_STOPSIGN_STOPTYPE.containing_type = _STOPSIGN
_STOPLINE.fields_by_name['stop_line'].message_type = geometry__pb2._POLYLINE
DESCRIPTOR.message_types_by_name['StopSign'] = _STOPSIGN
DESCRIPTOR.message_types_by_name['StopLine'] = _STOPLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopSign = _reflection.GeneratedProtocolMessageType('StopSign', (_message.Message,), dict(
    DESCRIPTOR=_STOPSIGN,
    __module__='map_stop_sign_pb2'
    # @@protoc_insertion_point(class_scope:deeproute.hdmap.StopSign)
))
_sym_db.RegisterMessage(StopSign)

StopLine = _reflection.GeneratedProtocolMessageType('StopLine', (_message.Message,), dict(
    DESCRIPTOR=_STOPLINE,
    __module__='map_stop_sign_pb2'
    # @@protoc_insertion_point(class_scope:deeproute.hdmap.StopLine)
))
_sym_db.RegisterMessage(StopLine)


_STOPLINE.fields_by_name['traffic_light_id'].has_options = True
_STOPLINE.fields_by_name['traffic_light_id']._options = _descriptor._ParseOptions(
    descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
