# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic_light_detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='traffic_light_detection.proto',
  package='deeproute.perception',
  syntax='proto2',
  serialized_pb=_b('\n\x1dtraffic_light_detection.proto\x12\x14\x64\x65\x65proute.perception\"\xdd\x02\n\x0cTrafficLight\x12\x37\n\x05\x63olor\x18\x01 \x01(\x0e\x32(.deeproute.perception.TrafficLight.Color\x12\x1b\n\x13traffic_light_token\x18\x02 \x01(\x05\x12\x15\n\nconfidence\x18\x03 \x01(\x01:\x01\x31\x12\x15\n\rtracking_time\x18\x04 \x01(\x01\x12\r\n\x05\x62link\x18\x05 \x01(\x08\x12\x16\n\x0eremaining_time\x18\x06 \x01(\x01\x12\x0f\n\x07task_id\x18\x07 \x01(\x05\x12\x12\n\ntime_stamp\x18\x08 \x01(\x01\x12<\n\x0ctraffic_type\x18\t \x01(\x0e\x32&.deeproute.perception.TrafficLightType\"?\n\x05\x43olor\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03RED\x10\x01\x12\n\n\x06YELLOW\x10\x02\x12\t\n\x05GREEN\x10\x03\x12\t\n\x05\x42LACK\x10\x04\"\x87\x01\n\x19TrafficLightDetectionTask\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x1b\n\x13traffic_light_token\x18\x02 \x03(\x05\x12<\n\x0ctraffic_type\x18\x03 \x01(\x0e\x32&.deeproute.perception.TrafficLightType\"R\n\x14TrafficLightResponse\x12:\n\x0etraffic_lights\x18\x01 \x03(\x0b\x32\".deeproute.perception.TrafficLight*L\n\x10TrafficLightType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\x12\t\n\x05UTURN\x10\x04')
)

_TRAFFICLIGHTTYPE = _descriptor.EnumDescriptor(
  name='TrafficLightType',
  full_name='deeproute.perception.TrafficLightType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UTURN', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=629,
  serialized_end=705,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICLIGHTTYPE)

TrafficLightType = enum_type_wrapper.EnumTypeWrapper(_TRAFFICLIGHTTYPE)
UNKNOWN = 0
FORWARD = 1
LEFT = 2
RIGHT = 3
UTURN = 4


_TRAFFICLIGHT_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='deeproute.perception.TrafficLight.Color',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=342,
  serialized_end=405,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICLIGHT_COLOR)


_TRAFFICLIGHT = _descriptor.Descriptor(
  name='TrafficLight',
  full_name='deeproute.perception.TrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='deeproute.perception.TrafficLight.color', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_light_token', full_name='deeproute.perception.TrafficLight.traffic_light_token', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='deeproute.perception.TrafficLight.confidence', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_time', full_name='deeproute.perception.TrafficLight.tracking_time', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blink', full_name='deeproute.perception.TrafficLight.blink', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remaining_time', full_name='deeproute.perception.TrafficLight.remaining_time', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='deeproute.perception.TrafficLight.task_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='deeproute.perception.TrafficLight.time_stamp', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_type', full_name='deeproute.perception.TrafficLight.traffic_type', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRAFFICLIGHT_COLOR,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=405,
)


_TRAFFICLIGHTDETECTIONTASK = _descriptor.Descriptor(
  name='TrafficLightDetectionTask',
  full_name='deeproute.perception.TrafficLightDetectionTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='deeproute.perception.TrafficLightDetectionTask.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_light_token', full_name='deeproute.perception.TrafficLightDetectionTask.traffic_light_token', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_type', full_name='deeproute.perception.TrafficLightDetectionTask.traffic_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=543,
)


_TRAFFICLIGHTRESPONSE = _descriptor.Descriptor(
  name='TrafficLightResponse',
  full_name='deeproute.perception.TrafficLightResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traffic_lights', full_name='deeproute.perception.TrafficLightResponse.traffic_lights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=627,
)

_TRAFFICLIGHT.fields_by_name['color'].enum_type = _TRAFFICLIGHT_COLOR
_TRAFFICLIGHT.fields_by_name['traffic_type'].enum_type = _TRAFFICLIGHTTYPE
_TRAFFICLIGHT_COLOR.containing_type = _TRAFFICLIGHT
_TRAFFICLIGHTDETECTIONTASK.fields_by_name['traffic_type'].enum_type = _TRAFFICLIGHTTYPE
_TRAFFICLIGHTRESPONSE.fields_by_name['traffic_lights'].message_type = _TRAFFICLIGHT
DESCRIPTOR.message_types_by_name['TrafficLight'] = _TRAFFICLIGHT
DESCRIPTOR.message_types_by_name['TrafficLightDetectionTask'] = _TRAFFICLIGHTDETECTIONTASK
DESCRIPTOR.message_types_by_name['TrafficLightResponse'] = _TRAFFICLIGHTRESPONSE
DESCRIPTOR.enum_types_by_name['TrafficLightType'] = _TRAFFICLIGHTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrafficLight = _reflection.GeneratedProtocolMessageType('TrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHT,
  __module__ = 'traffic_light_detection_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.perception.TrafficLight)
  ))
_sym_db.RegisterMessage(TrafficLight)

TrafficLightDetectionTask = _reflection.GeneratedProtocolMessageType('TrafficLightDetectionTask', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHTDETECTIONTASK,
  __module__ = 'traffic_light_detection_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.perception.TrafficLightDetectionTask)
  ))
_sym_db.RegisterMessage(TrafficLightDetectionTask)

TrafficLightResponse = _reflection.GeneratedProtocolMessageType('TrafficLightResponse', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHTRESPONSE,
  __module__ = 'traffic_light_detection_pb2'
  # @@protoc_insertion_point(class_scope:deeproute.perception.TrafficLightResponse)
  ))
_sym_db.RegisterMessage(TrafficLightResponse)


# @@protoc_insertion_point(module_scope)
